name: CI/CD with Helm

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-helm-demo:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx-helm-demo:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy using Helm
      run: |
        helm upgrade --install webapp ./webapp \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/nginx-helm-demo \
          --set image.tag=${{ github.sha }}
